server:
  port: 8012
  compression:
    enabled: true
logging:
  level:
    root: debug
    org.springframework.security: DEBUG
  file: demo.log
  path: c:/
spring:
  datasource:
    url: null
    data-password: null
    data-username: null
  thymeleaf:
    cache: false
amazon:
  associateId: habuma-20